In [ ]:
#code source: http://occam.olin.edu/sites/default/files/DataScienceMaterials/machine_learning_lecture_2/Machine%20Learning%20Lecture%202.html
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import *
from sklearn.linear_model import LogisticRegression

data = load_breast_cancer() #refer: http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html#sklearn.datasets.load_breast_cancer

tuned_parameters = [{'C': [10**-4, 10**-2, 10**0, 10**2, 10**4]}]
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, train_size=.7)


#Using GridSearchCV
model = GridSearchCV(LogisticRegression(solver = 'liblinear',max_iter = 100), tuned_parameters, scoring = 'f1', cv=5)
model.fit(X_train, y_train)

print(model.best_estimator_)
print(model.score(X_test, y_test))
#print(model.best_score_)
#print(model.cv_results_)

LogisticRegression(C=100, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
0.9545454545454546


In [ ]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
X_test.shape

(171, 30)

In [ ]:
import numpy as np

clf = LogisticRegression(C=100,solver ='liblinear');
clf.fit(X_train, y_train);
pred = clf.predict(X_test[:5])
print(pred)
print(y_test[:5])
pred_prob_xtest = clf.predict_proba(X_test[:5]) ## class probabilities
print(pred_prob_xtest)
scores = clf.score(X_test, y_test)
print(scores)
#print(clf.get_params())
dec_func = clf.decision_function(X_test)
print(dec_func[170])

[0 0 1 1 1]
[1 0 1 1 1]
[[8.27996365e-01 1.72003635e-01]
 [9.99999374e-01 6.25563494e-07]
 [2.43540705e-05 9.99975646e-01]
 [4.06009053e-05 9.99959399e-01]
 [7.29062936e-06 9.99992709e-01]]
0.9415204678362573
-38.3147583741947


In [ ]:
# More Sparsity (Fewer elements of W* being non-zero) by increasing Lambda (decreasing C) 

import numpy as np

clf = LogisticRegression(C=0.1, penalty='l1',solver ='liblinear',max_iter = 1000);
clf.fit(X_train, y_train);
w = clf.coef_
print(w)
print(np.count_nonzero(w))


[[ 0.         -0.0459092   0.51653416 -0.01757849  0.          0.
   0.          0.          0.          0.          0.          0.
   0.         -0.0538309   0.          0.          0.          0.
   0.          0.          0.         -0.09827441 -0.2140236  -0.01010062
   0.          0.          0.          0.          0.          0.        ]]
7


In [ ]:
clf = LogisticRegression(C=0.01, penalty='l1',solver ='liblinear');
clf.fit(X_train, y_train);
w = clf.coef_
print(np.count_nonzero(w))


4


In [ ]:
clf = LogisticRegression(C=0.001, penalty='l1',solver ='liblinear');
clf.fit(X_train, y_train);
w = clf.coef_
print(np.count_nonzero(w))


3


In [ ]:
clf = LogisticRegression(C=10, penalty='l1',solver ='liblinear');
clf.fit(X_train, y_train);
w = clf.coef_
print(np.count_nonzero(w))

16


In [ ]:
w

array([[ 0.        ,  0.        ,  0.05325029,  0.00551424,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        , -0.00988071,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])